---
# tasks file for postgres
- name: Install PostgreSQL and dependencies
  yum:
    name:
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
    state: present

- name: Initialize PostgreSQL database (if not already initialized)
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure sharedappdb database exists
  become_user: postgres
  community.postgresql.postgresql_db:
    name: sharedappdb
    state: present

- name: Ensure devops user exists
  community.postgresql.postgresql_user:
    name: devops
    password: "{{ db_password }}"
    role_attr_flags: LOGIN

- name: Ensure devops user has correct password
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: LOGIN
    state: present

- name: Copy schema file to server
  copy:
    src: db/init.sql
    dest: /tmp/init.sql
    mode: '0644'

- name: Apply schema (only once)
  become_user: postgres
  command: psql -d sharedappdb -f /tmp/init.sql
  args:
    creates: /tmp/schema_done.marker

- name: Mark schema as applied
  file:
    path: /tmp/schema_done.marker
    state: touch
