---
# tasks file for postgres

- name: Install PostgreSQL packages
  yum:
    name:
      - postgresql-server
      - postgresql-contrib
      - postgresql-devel
      - python3-psycopg2
    state: present

- name: Initialize PostgreSQL database if not already
  command: /usr/bin/postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Deploy pg_hba.conf with md5 auth
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
  notify: Restart PostgreSQL

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure DB user exists
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present

- name: Ensure database exists
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present

- name: Ensure devs table exists
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    query: |
      CREATE TABLE IF NOT EXISTS devs (
        id SERIAL PRIMARY KEY,
        name VARCHAR(50) UNIQUE
      );

- name: Grant privileges to app user
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    query: "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ db_user }};"

- name: Seed devs table with sample data
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    query: |
      INSERT INTO devs (name)
      VALUES 
        ('Flask Developer'),
        ('Node Developer'),
        ('Shared DB User')
      ON CONFLICT (name) DO NOTHING;
