---
# tasks file for postgres
# Install PostgreSQL and set up DB schema + seed data

- name: Install PostgreSQL packages
  yum:
    name:
      - postgresql-server
      - postgresql-contrib
      - postgresql-devel
      - python3-psycopg2
    state: present

- name: Initialize PostgreSQL database
  command: /usr/bin/postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure devops user exists
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present

- name: Ensure sharedappdb database exists
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    state: present

- name: Ensure devs table exists
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    query: |
      CREATE TABLE IF NOT EXISTS devs (
        id SERIAL PRIMARY KEY,
        name VARCHAR(50) UNIQUE
      );

- name: Seed devs table with sample data
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    query: |
      INSERT INTO devs (name)
      VALUES 
        ('Flask Developer'),
        ('Node Developer'),
        ('Shared DB User')
      ON CONFLICT (name) DO NOTHING;
