---
# tasks file for nodejs
- name: Add Node.js repo
  get_url:
    url: https://rpm.nodesource.com/setup_20.x
    dest: /tmp/nodesource_setup.sh
    mode: 0755

- name: Run Node.js setup
  command: bash /tmp/nodesource_setup.sh

- name: Install Node.js and npm
  yum:
    name: nodejs
    state: present

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Create node app directory
  file:
    path: /opt/node-app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Copy Node.js source code
  copy:
    src: ../../node-app/
    dest: /opt/node-app/
    owner: ec2-user
    group: ec2-user

- name: Create PM2 ecosystem file
  copy:
    dest: /opt/node-app/ecosystem.config.js
    content: |
      module.exports = {
        apps: [
          {
            name: "node-app",
            script: "index.js",
            env: {
              DB_HOST: "{{ db_host }}",
              DB_NAME: "{{ db_name }}",
              DB_USER: "{{ db_user }}",
              DB_PASS: "{{ db_pass }}",
              DB_PORT: {{ db_port }}
            }
          }
        ]
      };
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Start Node app with PM2
  command: pm2 start ecosystem.config.js
  args:
    chdir: /opt/node-app

- name: Save PM2 process list
  command: pm2 save
