---
# tasks file for nodejs
- name: Install Node.js
  yum:
    name: nodejs
    state: present

- name: Copy Node.js app
  copy:
    src: ../../node-app/
    dest: /home/ec2-user/node-app/
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Install Node.js dependencies
  command: npm install
  args:
    chdir: /home/ec2-user/node-app

- name: Deploy systemd service for Node.js
  template:
    src: node.service.j2
    dest: /etc/systemd/system/node.service
  notify: Restart Node.js

