---
# tasks file for flask
- name: Install Python and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Flask and psycopg2
  pip:
    name:
      - flask
      - psycopg2-binary

- name: Copy Flask app
  copy:
    src: ../../flask-app/
    dest: /home/ec2-user/flask-app/
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Deploy systemd service for Flask
  template:
    src: flask.service.j2
    dest: /etc/systemd/system/flask.service
  notify: Restart Flask
